language: cpp

dist: xenial
sudo: required

matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          packages:
            - libboost1.58-dev
            - libboost-regex1.58
            - libboost-thread1.58
            - libboost-system1.58
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - sourceline: 'ppa:mhier/libboost-latest'
          packages:
            - g++-8
            - libboost1.68-dev
            - libboost1.68
      env: COMPILER=g++-8
    - os: osx
      compiler: clang
      osx_image: xcode10.1
      env: COMPILER=clang++
before_install:
  # Linux
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get update -qq; 
        sudo apt-get install -y cmake nodejs python pkg-config libbz2-dev zlib1g-dev libssl-dev libstdc++6 libminiupnpc-dev libnatpmp-dev libtbb-dev libmaxminddb-dev libleveldb-dev;
    fi
  # OSX
  - if [ $TRAVIS_OS_NAME == osx ]; then brew update;
        brew install boost libmaxminddb leveldb libnatpmp miniupnpc openssl pkg-config tbb;
        export OPENSSL_ROOT_DIR=/usr/local/opt/openssl/;
    fi

  - git clone git://github.com/zaphoyd/websocketpp.git
  - cd websocketpp
  - cmake .
  - sudo make install
  - cd ..
script:
  - CXXFLAGS=-Werror cmake -DCMAKE_CXX_COMPILER=$COMPILER . && make -j2 && sudo make install
  - if [ $TRAVIS_OS_NAME == linux ]; then
        sh ./test/initial_run.sh;
    fi
branches:
  only:
    - master
    - develop
